source 'http://rubygems.org'

gem 'twitter'
gem 'mongo'
gem 'mongo_mapper'
gem 'cloudq'
gem 'cloudq_client'
# gem 'json'
# gem 'sinatra'
# gem 'haml'
# gem 'json'
# gem 'rest-client'
# gem 'httparty'
# gem 'curb'